### ISSUE TITLE
[FEEDBACK] some recreational commands

### ISSUE THREAD

**Issue by CMAutoIssue** [ewang2002/ZeroRaidBot#100]
### Version
0.7.0-pre.1

### Feedback
;roll {max} - Rolls number from 1 to the stated number.
;russianroulette {bullets} - Allows 1-5 bullets to be loaded and responds if you survived or died.
;anagram - Pulls a random word from a massive text file with a bunch of words, and scrambles it. First one to type it in the corresponding channel(within 30 seconds) wins.
;coinflip - Returns head or tails.

### Submitter ("User") Information
Discord Tag: thedrdu#2310
Discord ID: 293555682475507724
Date/Time Submitted: 12/6/2020, 10:17:37 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
I do not plan on adding this because this does not fit with the bot's purpose.
