### ISSUE TITLE
[FEEDBACK] Add stop/close button on mod mail threads on each of the responses we send to them

### ISSUE THREAD

**Issue by CMAutoIssue** [ewang2002/ZeroRaidBot#91]
### Version
0.6.2-pre.5

### Feedback
Add stop/close button on mod mail threads on each of the responses we send to them so that we can close it easier instead of having to scroll all the way to the top

### Submitter Information
Discord Tag: Karma's Guide#6864
Discord ID: 165929337869041665
Date/Time Submitted: 10/11/2020, 2:05:58 PM

### Disclaimer: PLEASE READ
This issue was NOT written by the author of the repository OR the account that posted this issue. This issue was submitted through the program hosted in this repository, via Github's API, by someone that uses the program ("user"). The user can be found above.

**Comment by ewang2002** [comment]
The bot automatically pins the message that has the stop/blacklist reactions. As such, I do not believe this is needed.
